2-dev:
  haml: '\PHPixie\Haml'
3-dev: # todo
  db: '\PHPixie\Database'
  orm: '\PHPixie\ORM'
  auth: '\PHPixie\Auth'
  email: '\PHPixie\Email'
  image: '\PHPixie\Image'
  cache: '\PHPixie\Cache'
  slice: '\PHPixie\Slice'
  http: '\PHPixie\HTTP'
  security: '\PHPixie\Security'
  authLogin: '\PHPixie\AuthLogin'
