api:
  - '/api/v<version>/<controller>(/<action>(/<data>))'
  -
    action: 'default'
    __API__: 1

default:
  - '(/<controller>(/<action>(/<id>)))'
  -
    controller: 'hello'
    action: 'default'